title: "ë‚´ ê¹ƒí—ˆë¸Œ ë¸”ë¡œê·¸ ğŸš€"
description: "ë°ì´í„° ë¶„ì„ & AI ì´ì•¼ê¸°"
theme: jekyll-theme-modernist
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
include: 
  - _data/navigation.yml  
sidebar:
  nav: "main"
permalink: /:categories/:title/
